#!/bin/sh -e

BIN=""
if [ -d venv ] ; then
    BIN="venv/bin/"
fi

SOURCE_FILES="src"

set -x

${BIN}black --check --diff --target-version=py38 $SOURCE_FILES
${BIN}flake8 $SOURCE_FILES
${BIN}mypy $SOURCE_FILES
