#!/bin/sh -e

BIN=""
if [ ! -d venv ]; then
  BIN="venv/bin/"
fi

PROXYX_HOSTNAME=${PROXYX_HOSTNAME:-www.python-httpx.org} PROXYX_ROOT_PATH=${PROXYX_ROOT_PATH:-} ${BIN}uvicorn example:app --port=${PORT:-8000}
